### ISSUE TITLE
onion_set_port() causes segfault during request

### ISSUE THREAD

**Issue by msoulier** [davidmoreno/onion#118]
msoulier@cappuccino:...-proj/mitool-mgmt$ cat hello.c
    #include <onion/onion.h>
    #include <onion/log.h>
    #include <onion/request.h>
    #include <onion/response.h>

    #define HELLO_LENGTH 13

    int hello(void *p, onion_request *req, onion_response *res) {
        onion_response_set_length(res, HELLO_LENGTH);
        onion_response_write(res, "Hello, World!", HELLO_LENGTH);
        return OCS_PROCESSED;
    }

    int main(int argc, char **argv) {
        onion *o = onion_new(O_THREADED);
        if (argc > 1) {
            ONION_INFO("Setting listen port to %s", argv[1]);
            onion_set_port(o, argv[1]);
        }
        else {
            ONION_INFO("Defaulting to listen port 8080");
        }
        onion_set_certificate(o, O_SSL_CERTIFICATE_KEY, "ssl-cert-snakeoil.pem",
                                                    "ssl-cert-snakeoil.key",
                                                    O_SSL_NONE);

        onion_url *urls = onion_root_url(o);

        onion_url_add_static(urls, "^static$", "Hello static world", HTTP_OK);
        onion_url_add(urls, "^$", hello);

        onion_listen(o);
        onion_free(o);
        return 0;
    }

Pretty simple. If I don't supply an argument everything works. If I supply one, like 8080, then when the request from the browser is made, libonion segfaults. 

Core was generated by `./hello 8080'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004073c5 in onion_listen_point_request_init_from_socket ()
(gdb) bt
#0  0x00000000004073c5 in onion_listen_point_request_init_from_socket ()
#1  0x000000000040a1e0 in onion_https_request_init ()
#2  0x00000000004046a3 in onion_request_new ()
#3  0x0000000000406feb in onion_listen_point_accept ()
#4  0x000000000040af35 in onion_poller_poll ()
#5  0x0000000000402ffc in onion_poller_poll_start ()
#6  0x00007fd411c490a4 in start_thread (arg=0x7fd40f71e700) at pthread_create.c:309
#7  0x00007fd41137d04d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

This is on Debian Jessie. Using latest libonion out of git. 

msoulier@cappuccino:...l-mgmt-proj/onion$ git log -1
commit 2293b2a3123f4310cc1c947a4346faa1b9685a49
Author: David Moreno <dmoreno@coralbits.com>
Date:   Tue Sep 1 12:13:16 2015 +0200

    Compilation fix: Return 0 from main at longpoll.

**Comment by zacharygrafton** [comment]
msoulier,

Did you happen to build Onion with systemd support? I think I've been able to pinpoint a problem in the code, but it only happens with systemd support built in.

Zack
