### ISSUE TITLE
onion malloc(): unsorted double linked list corrupted

### ISSUE THREAD

**Issue by tianwen2976** [davidmoreno/onion#290]
I use onion to handle http requests, and the program exits abnormally.  version: master 

`malloc(): unsorted double linked list corrupted`

```
#0  0x00007f8375cce7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8375cb9535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f8375d10508 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f8375d16c1a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f8375d19cfc in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007f8375d1c1a2 in calloc () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f8376685de6 in onion_low_calloc () from /xxx/lib/libonion.so.0
#7  0x00007f8376686698 in onion_request_new () from /xxx/lib/libonion.so.0
#8  0x00007f8376689c6b in onion_listen_point_accept () from /xxx/lib/libonion.so.0
#9  0x00007f837668e338 in onion_poller_poll () from /xxx/lib/libonion.so.0
#10 0x00007f83766838f5 in onion_listen () from /xxx/lib/libonion.so.0
#11 0x00007f837668397c in onion_listen_start () from /xxx/lib/libonion.so.0
#12 0x00007f837669ffa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#13 0x00007f8375d904cf in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
Has anyone else encountered it before？

**Comment by tianwen2976** [comment]
My own question
